### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [crossphd/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by sigef** [comment]
Thanks Billy, I added the meta viewport tag for mobile and pushed it to production. Thanks!

**Comment by crossphd** [comment]
Oops, didn't realize I wasn't logged into my new github account.
